name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Frontend
        run: |
          cd client
          npm ci
          npm run build

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "client/dist/**,server/**,infrastructure/nginx.conf_new"
          target: "/home/ec2-user/task-manager-devops"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Update Frontend files
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /home/ec2-user/task-manager-devops/client/dist/* /usr/share/nginx/html/
            
            # Update Nginx Config
            sudo mv /home/ec2-user/task-manager-devops/infrastructure/nginx.conf_new /etc/nginx/nginx.conf
            sudo systemctl restart nginx
            
            # Create .env file at the root (where the app looks for it)
            echo "PORT=5000" > /home/ec2-user/task-manager-devops/.env
            echo "JWT_SECRET=presidio_secret_key_123" >> /home/ec2-user/task-manager-devops/.env
            echo "COOKIE_NAME=auth_token" >> /home/ec2-user/task-manager-devops/.env
            echo "JWT_EXPIRES_IN=1h" >> /home/ec2-user/task-manager-devops/.env
            echo "COOKIE_MAX_AGE=3600000" >> /home/ec2-user/task-manager-devops/.env
            
            # Start Backend
            cd /home/ec2-user/task-manager-devops/server
            npm install
            
            if ! command -v pm2 &> /dev/null
            then
                sudo npm install -g pm2
            fi
            
            pm2 delete task-manager-api || true
            pm2 start server.js --name "task-manager-api"
            pm2 save
